//---------------------------------------------------------------------------

#ifndef Unit3H
#define Unit3H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TShape *s1;
        TShape *s13;
        TShape *s48;
        TShape *s2;
        TShape *s5;
        TShape *s30;
        TShape *s23;
        TShape *s34;
        TShape *s7;
        TShape *s9;
        TShape *s10;
        TShape *s11;
        TShape *s12;
        TShape *s14;
        TShape *s15;
        TShape *s16;
        TShape *s17;
        TShape *s18;
        TShape *s20;
        TShape *s19;
        TShape *s21;
        TShape *s22;
        TShape *s24;
        TShape *s25;
        TShape *s26;
        TShape *s28;
        TShape *s27;
        TShape *s29;
        TShape *s31;
        TShape *s32;
        TShape *s33;
        TShape *s35;
        TShape *s36;
        TShape *s38;
        TShape *s39;
        TShape *s37;
        TShape *s40;
        TShape *s41;
        TShape *s42;
        TShape *s43;
        TShape *s44;
        TShape *s46;
        TTimer *left_pacman_timer;
        TImage *pacman;
        TTimer *right_pacman_timer;
        TTimer *up_pacman_timer;
        TTimer *down_pacman_timer;
        TShape *s3;
        TShape *s4;
        TShape *s6;
        TShape *s8;
        TShape *s45;
        TShape *s47;
        TImage *greenghost;
        TImage *redghost;
        TImage *blueghost;
        TImage *pinkghost;
        TTimer *red_vertical_timer;
        TTimer *green_tier_timer;
        TTimer *green_vertical_timer;
        TTimer *blue_vertical_timer;
        TTimer *blue_tier_timer;
        TTimer *pink_vertical_timer;
        TTimer *pink_tier_timer;
        TTimer *red_tier_timer;
        TButton *button1;
        TImage *life1;
        TImage *life2;
        TImage *life3;
        TImage *b1;
        TImage *b52;
        TImage *b62;
        TImage *b73;
        TImage *b84;
        TImage *b95;
        TImage *b106;
        TImage *b117;
        TImage *b128;
        TImage *b2;
        TImage *b13;
        TImage *b24;
        TImage *b35;
        TImage *b46;
        TImage *b47;
        TImage *b48;
        TImage *b49;
        TImage *b50;
        TImage *b51;
        TImage *b53;
        TImage *b54;
        TImage *b55;
        TImage *b56;
        TImage *b57;
        TImage *b58;
        TImage *b59;
        TImage *b43;
        TImage *b60;
        TImage *b61;
        TImage *b63;
        TImage *b64;
        TImage *b65;
        TImage *b66;
        TImage *b67;
        TImage *b68;
        TImage *b69;
        TImage *b70;
        TImage *b71;
        TImage *b72;
        TImage *b74;
        TImage *b75;
        TImage *b76;
        TImage *b77;
        TImage *b78;
        TImage *b79;
        TImage *b80;
        TImage *b81;
        TImage *b82;
        TImage *b83;
        TImage *b85;
        TImage *b86;
        TImage *b87;
        TImage *b88;
        TImage *b89;
        TImage *b90;
        TImage *b91;
        TImage *b92;
        TImage *b93;
        TImage *b94;
        TImage *b96;
        TImage *b97;
        TImage *b98;
        TImage *b99;
        TImage *b100;
        TImage *b101;
        TImage *b102;
        TImage *b103;
        TImage *b104;
        TImage *b105;
        TImage *b107;
        TImage *b108;
        TImage *b109;
        TImage *b110;
        TImage *b111;
        TImage *b112;
        TImage *b113;
        TImage *b114;
        TImage *b115;
        TImage *b116;
        TImage *b118;
        TImage *b119;
        TImage *b120;
        TImage *b121;
        TImage *b122;
        TImage *b123;
        TImage *b124;
        TImage *b125;
        TImage *b126;
        TImage *b127;
        TImage *b129;
        TImage *b130;
        TImage *b131;
        TImage *b132;
        TImage *b133;
        TImage *b134;
        TImage *b135;
        TImage *b136;
        TImage *b137;
        TImage *b138;
        TImage *b3;
        TImage *b4;
        TImage *b5;
        TImage *b6;
        TImage *b7;
        TImage *b8;
        TImage *b9;
        TImage *b10;
        TImage *b11;
        TImage *b12;
        TImage *b14;
        TImage *b15;
        TImage *b16;
        TImage *b17;
        TImage *b18;
        TImage *b19;
        TImage *b20;
        TImage *b21;
        TImage *b22;
        TImage *b23;
        TImage *b25;
        TImage *b26;
        TImage *b27;
        TImage *b28;
        TImage *b29;
        TImage *b30;
        TImage *b31;
        TImage *b32;
        TImage *b33;
        TImage *b34;
        TImage *b36;
        TImage *b37;
        TImage *b38;
        TImage *b39;
        TImage *b40;
        TImage *b41;
        TImage *b42;
        TImage *b44;
        TImage *b45;
        TTimer *collision;
        TButton *button2;
        TTimer *eat_time_timer;
        TTimer *red_quarantine_timer;
        TTimer *green_quarantine_timer;
        TTimer *blue_quarantine_timer;
        TTimer *pink_quarantine_timer;
        TLabel *label;
        void __fastcall right_pacman_timerTimer(TObject *Sender);
        void __fastcall left_pacman_timerTimer(TObject *Sender);
        void __fastcall up_pacman_timerTimer(TObject *Sender);
        void __fastcall down_pacman_timerTimer(TObject *Sender);
        void __fastcall FormKeyDown(TObject *Sender, WORD &Key,
          TShiftState Shift);
        void __fastcall FormKeyUp(TObject *Sender, WORD &Key,
          TShiftState Shift);
        void __fastcall red_tier_timerTimer(TObject *Sender);
        void __fastcall red_vertical_timerTimer(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall green_tier_timerTimer(TObject *Sender);
        void __fastcall green_vertical_timerTimer(TObject *Sender);
        void __fastcall blue_tier_timerTimer(TObject *Sender);
        void __fastcall pink_tier_timerTimer(TObject *Sender);
        void __fastcall blue_vertical_timerTimer(TObject *Sender);
        void __fastcall pink_vertical_timerTimer(TObject *Sender);
        void __fastcall collisionTimer(TObject *Sender);
        void __fastcall eat_time_timerTimer(TObject *Sender);
        void __fastcall red_quarantine_timerTimer(TObject *Sender);
        void __fastcall green_quarantine_timerTimer(TObject *Sender);
        void __fastcall blue_quarantine_timerTimer(TObject *Sender);
        void __fastcall pink_quarantine_timerTimer(TObject *Sender);
        void __fastcall button2Click(TObject *Sender);
        void __fastcall button1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
